eureka:
instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
build:
  version: "1.0"


accounts:
  message: "Welcome to DreamBank accounts related local APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Developer"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 1234567898"
    - "(+91) 1234567896"

    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
    
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"
