eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
build:
  version: "1.0"


accounts:
  message: "Welcome to DreamBank accounts related local APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Developer"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 1234567898"
    - "(+91) 1234567896"
