spring:
  cloud:
    gateway:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
build:
  version: "1.0"

    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
    
info:
  app:
    name: "API GATEWAY"
    description: "API GATEWAY for Eazy Bank Microservice"
    version: "1.0.0"
