

build:
  version: "1.0"


loans:
  message: "Welcome to DreamBank loans related PROD APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Production"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 02020202"
    - "(+91) 1111111111"
