
build:
  version: "1.0"


loans:
  message: "Welcome to DreamBank loans related local APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Production"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 1111111111"
    - "(+91) 1111111111"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: "loans"
    description: "Dream Bank Accounts Application"
    version: "1.0.0"
